[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn bricoleup.wsgi --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
