# Generated by Django 5.1 on 2025-04-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='add_to_search',
            field=models.BooleanField(default=False),
        ),
    ]
