# Generated by Django 5.1 on 2025-04-15 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile_add_to_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='identity_type',
            field=models.CharField(choices=[('particulier', 'Particulier'), ('professionnel', 'Professionnel')], default='particulier', max_length=20),
        ),
        migrations.CreateModel(
            name='VerificationRequestPro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('company_id', models.CharField(blank=True, max_length=100)),
                ('activity', models.CharField(blank=True, max_length=255)),
                ('pro_document_file', models.FileField(blank=True, null=True, upload_to='business_documents/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_comment', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests_pro', to='app.profile')),
            ],
        ),
    ]
