# Generated by Django 5.1 on 2025-04-19 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_profile_identity_type_verificationrequestpro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationrequest',
            name='selfie_file',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
