# Generated by Django 5.1 on 2025-04-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_verificationrequest_selfie_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='message_privacy',
            field=models.CharField(choices=[('everyone', 'Tout le monde'), ('members', 'Seulement les membres de BricoleUp'), ('verified_members', 'Seulement les membres vérifiés')], default='everyone', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_visibility',
            field=models.CharField(choices=[('everyone', 'Tout le monde'), ('members', 'Seulement les membres de BricoleUp'), ('verified_members', 'Seulement les membres vérifiés')], default='everyone', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='request_privacy',
            field=models.CharField(choices=[('everyone', 'Tout le monde'), ('members', 'Seulement les membres de BricoleUp'), ('verified_members', 'Seulement les membres vérifiés')], default='everyone', max_length=20),
        ),
    ]
