# Generated by Django 5.1 on 2025-05-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile_message_privacy_profile_profile_visibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='completion_score',
            field=models.IntegerField(default=0),
        ),
    ]
