# Generated by Django 5.1 on 2025-07-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_project_content_project_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='adresse',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='statut',
            field=models.CharField(choices=[('particulier', 'Particulier'), ('independant', 'Indépendant'), ('autoentrepreneur', 'Auto-entrepreneur'), ('entreprise', 'Entreprise')], default='particulier', max_length=20),
        ),
    ]
