# Generated by Django 5.1 on 2025-09-05 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_city_name_ar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='name_ar',
        ),
    ]
