# Generated by Django 5.1 on 2025-09-06 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_city_name_ar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='flag',
        ),
        migrations.RemoveField(
            model_name='country',
            name='name_ar',
        ),
    ]
