# Generated by Django 5.1 on 2025-09-10 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_country_flag_remove_country_name_ar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
