# Generated by Django 5.1 on 2025-09-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_conversations_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(choices=[(1.0, '1.0'), (2.0, '2.0'), (3.0, '3.0'), (4.0, '4.0'), (5.0, '5.0')], default=0.0),
        ),
    ]
