# Generated by Django 5.1 on 2025-09-13 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_picture',
            field=models.ImageField(blank=True, null=True, upload_to='cover_pictures/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(choices=[(1.0, '1.0'), (2.0, '2.0'), (3.0, '3.0'), (4.0, '4.0'), (5.0, '5.0')], default=5.0),
        ),
    ]
