# Generated by Django 5.1 on 2025-09-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_profile_cover_picture_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
