# Generated by Django 5.1 on 2025-11-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_profile_code_ape_profile_date_creation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='title',
        ),
        migrations.AddField(
            model_name='announcement',
            name='a_convenir',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='statut',
            field=models.CharField(choices=[('particulier', 'Particulier'), ('entreprise', 'Entreprise')], default='particulier', max_length=20),
        ),
    ]
