# Generated by Django 5.1 on 2025-11-08 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_announcement_slug_remove_announcement_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='identity_type',
        ),
    ]
