# Generated by Django 5.1 on 2025-11-09 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_profile_identity_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='icon_class',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='subskill',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='subskill',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='subsubskill',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='subsubskill',
            name='name_en',
        ),
    ]
