# Generated by Django 5.1 on 2025-11-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_skill_icon_class_remove_skill_name_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(blank=True, to='app.skill'),
        ),
    ]
