# Generated by Django 5.1.1 on 2025-11-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_project_image5_remove_project_image6_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('welcome', 'Bienvenue'), ('announcement_published_owner', 'Annonce publiée (owner)'), ('announcement_published_city', 'Annonce publiée (city users)'), ('project_published_owner', 'Projet publiée (owner)')], default='welcome', max_length=50),
        ),
    ]
