# Generated by Django 5.1.1 on 2025-12-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_notification_metadata_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
