# Generated by Django 5.1.1 on 2026-01-04 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_announcement_email_sent_message_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_otp',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
