# Generated by Django 5.1.1 on 2026-01-04 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_profile_phone_otp_profile_phone_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_otp',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
