# Generated by Django 5.1.1 on 2026-01-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_profile_email_otp_profile_email_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='document_entreprise',
            field=models.FileField(blank=True, null=True, upload_to='verifications/entreprises/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='piece_identite',
            field=models.FileField(blank=True, null=True, upload_to='verifications/pieces_identite/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='selfie_verification',
            field=models.ImageField(blank=True, null=True, upload_to='verifications/selfies/'),
        ),
    ]
