# Generated by Django 5.1.1 on 2026-01-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_profile_document_entreprise_profile_piece_identite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_status',
            field=models.CharField(choices=[('non_verifie', 'Non vérifié'), ('en_cours', 'En cours'), ('verifie', 'Vérifié'), ('refuse', 'Refusé')], default='non_verifie', max_length=20),
        ),
    ]
