# Generated by Django 5.1.1 on 2026-01-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_profile_verification_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='budget',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
