# Generated by Django 5.1.1 on 2026-01-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_announcement_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_identity_verify_pay',
            field=models.BooleanField(default=False),
        ),
    ]
