# Generated by Django 5.0.6 on 2026-05-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_remove_profile_add_to_search_remove_profile_adresse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='abonnement',
            field=models.CharField(choices=[('gratuit', 'Gratuit'), ('pro', 'Pro')], default='gratuit', max_length=20),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('refused', 'Refusée')], default='pending', max_length=20),
        ),
    ]
