# Generated by Django 5.0.6 on 2026-05-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_profile_abonnement_alter_offer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='moderation_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée')], db_index=True, default='pending', max_length=20),
        ),
    ]
