# Generated by Django 5.0.6 on 2026-05-09 18:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_announcement_moderation_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('welcome', 'Bienvenue'), ('announcement_published_owner', 'Annonce publiée (owner)'), ('announcement_published_city', 'Annonce publiée (city users)'), ('project_published_owner', 'Projet publiée (owner)'), ('message', 'Nouveau message'), ('like', "J'aime sur portfolio"), ('comment', 'Commentaire sur portfolio'), ('review', 'Nouvel avis')], default='welcome', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('towork', 'I want to work'), ('tohire', 'I want to hire')], db_index=True, default='towork', max_length=20),
        ),
    ]
